# Generated by Django 3.1.7 on 2021-04-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='day',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='hour',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='month',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='priority',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='year',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Año'),
        ),
    ]
