# Generated by Django 3.1.7 on 2021-04-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=200)),
                ('edad', models.IntegerField(max_length=100, unique=True)),
            ],
        ),
    ]
