# Generated by Django 3.1.7 on 2021-04-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('password', models.CharField(max_length=200, verbose_name='Contraseña')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
