# Generated by Django 3.1.7 on 2021-04-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0001_initial'),
        ('Users', '0003_auto_20210405_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(to='Tags.Tag'),
        ),
    ]
